services:
  drachtio:
    image: drachtio/drachtio-server:latest
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "9022:9022/tcp"
    command: >
      drachtio --contact "sip:*:5060;transport=udp"
      --contact "sip:*:5060;transport=tcp"
      --loglevel info
      --sofia-loglevel 3
      --address 0.0.0.0
      --port 9022
      --secret cymru
    restart: always

  freeswitch:
    image: drachtio/drachtio-freeswitch-mrf:latest
    ports:
      - "8021:8021/tcp"
    restart: always
